<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MOHIT" failures="1" tests="12" name="com.hrm.HRM_SystemEmployee.AssertClassPract" time="0.044" errors="0" timestamp="2023-05-26T15:20:23 IST" skipped="0">
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="AssertEqualsTest" time="0.016"/>
  <system-out>
    <![CDATA[assert equals is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="Asserttrue" time="0.002"/>
  <system-out>
    <![CDATA[assert true is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="AssertEqualsTest1" time="0.002"/>
  <system-out>
    <![CDATA[assert equals is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="AssertEqualsTest4" time="0.002"/>
  <system-out>
    <![CDATA[assert equals is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="Assertfalse3" time="0.001"/>
  <system-out>
    <![CDATA[assert false is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="AssertEqualsTest2" time="0.002"/>
  <system-out>
    <![CDATA[assert equals is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="Assertfalse" time="0.006"/>
  <system-out>
    <![CDATA[assert false is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="Asserttrue1" time="0.005"/>
  <system-out>
    <![CDATA[assert true is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="AssertEqualsTest3" time="0.002"/>
  <system-out>
    <![CDATA[assert equals is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="Asserttrue2" time="0.001"/>
  <system-out>
    <![CDATA[assert true is pass----]]>
  </system-out>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="AssertException" time="0.002">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.hrm.HRM_SystemEmployee.AssertClassPract.AssertException(AssertClassPract.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AssertException -->
  <system-out/>
  <testcase classname="com.hrm.HRM_SystemEmployee.AssertClassPract" name="Asserttrue3" time="0.003"/>
  <system-out>
    <![CDATA[assert true is pass----]]>
  </system-out>
</testsuite> <!-- com.hrm.HRM_SystemEmployee.AssertClassPract -->
